## Class 4

* Dictionaries
* numpy
* mathplotlib

In [21]:
import urllib.request
link = "http://www.phy.bme.hu/~torok/Hun_cities_noacc.csv"
f = urllib.request.urlopen(link)
myfile = f.read()
f.close()
f = open("Hun_cities_noacc.csv","w")
f.write(str(myfile,"utf-8"))
f.close()

In [22]:
str(myfile,"utf-8").split('\n')[5]

'1941,"Pecs","Pecs",156801,16277,46.07308,18.22857,3207,1,2,1,1,4,1'

In [23]:
cities = []
for line in str(myfile,"utf-8").split('\n'):
    cities.append(line.split(','))
print(cities[0])
print(cities[5])

['KSHKOD', '"TELNEV CLEAR"', '"TELNEV CLEAR"', 'POP', 'SIZE_km2', 'latitude', 'longitude', 'SUBREG', 'SUBREGCENT', 'COUNTYCODE', 'COUNTYCENT', 'TOWN', 'REGION', 'UNIV']
['1941', '"Pecs"', '"Pecs"', '156801', '16277', '46.07308', '18.22857', '3207', '1', '2', '1', '1', '4', '1']


In [24]:
cities = []
with open("Hun_cities_noacc.csv","r") as f:
    for line in f:
        cities.append(line.rstrip().split(','))
print(cities[4])
print(cities[5])

['3045', '"Miskolc"', '"Miskolc"', '166823', '23666', '48.105625', '20.790556', '3501', '1', '5', '1', '1', '5', '1']
['1941', '"Pecs"', '"Pecs"', '156801', '16277', '46.07308', '18.22857', '3207', '1', '2', '1', '1', '4', '1']


### Dictionaries

Dictionaries are also like lists, except that each element is a key-value pair. The syntax for dictionaries is `{key1 : value1, key2 : value 2, ...}`:

In [2]:
D = {0 : k for k in ['a', 'b', 'c']}
print(D)

{0: 'c'}


In [3]:
fruits = {"bananas" : 1,
          "oranges" : 2,
          "apples" : 3,}

print(type(fruits))
print(fruits)

<class 'dict'>
{'bananas': 1, 'oranges': 2, 'apples': 3}


In [4]:
type(fruits.values())

dict_values

In [5]:
print("bananas = " + str(fruits["bananas"]))
print("oranges = " + str(fruits["oranges"]))
print("apples = " + str(fruits["apples"]))

bananas = 1
oranges = 2
apples = 3


In [6]:
fruits["bananas"] = "no bananas"
fruits["oranges"] = 100

# add a new entry
fruits["pineapples"] = "D"

print("bananas = " + str(fruits["bananas"]))
print("oranges = " + str(fruits["oranges"]))
print("apples = " + str(fruits["apples"]))
print("pineapples = " + str(fruits["pineapples"]))

bananas = no bananas
oranges = 100
apples = 3
pineapples = D


Strings, numbers, and tuples work as keys, and any type can be a value. Other types may or may not work correctly as keys (strings and tuples work cleanly since they are immutable). Looking up a value which is not in the dict throws a KeyError -- use "in" to check if the key is in the dict, or use dict.get(key) which returns the value or None if the key is not present (or get(key, not-found) allows you to specify what value to return in the not-found case).

In [7]:
print(fruits['bananas'])     ## Simple lookup, returns 'bananas'

no bananas


If you try to access something that does not exists in the dictionary, you will get an error:

In [8]:
print(fruits['strawberries'])

KeyError: 'strawberries'

To avoid key errors, you can simply check with an ``if`` that the key is present in the dictionary: 

In [9]:
if 'bananas' in fruits: print(fruits['bananas']) ## Yes, you can also write an if in this way 

if 'strawberries' in fruits: print (fruits['strawberries']) ## and an if-else in this way 
else: print("I don\'t know what a strawberry is")

no bananas
I don't know what a strawberry is


An alternative way to access keys in a dictionary is with the method ``get``. If the key does not exist you get a None:

In [10]:
print(fruits.get('bananas'))
print(fruits.get('strawberries')) 

no bananas
None


You can also define a default different from ```None``:

In [11]:
print(fruits.get('strawberries',0))  

0


To iterate over key-value pairs of a dictionary:

In [12]:
for key in fruits: 
    print(key, fruits[key])

bananas no bananas
oranges 100
apples 3
pineapples D


This iteration is equivalent to iterating over ```fruits.keys()```:

In [13]:
for key in fruits.keys(): 
    print(key)

bananas
oranges
apples
pineapples


In [14]:
type(fruits.keys())

dict_keys

If you want to show the values instead:

In [15]:
for value in fruits.values():
    print(value)

no bananas
100
3
D


In [16]:
type(fruits.values)

builtin_function_or_method

If you want to show both at the same time, you can use fruits.items()

In [17]:
for key, value in fruits.items():
    print(key + " = " + str(value))

bananas = no bananas
oranges = 100
apples = 3
pineapples = D


_**Note that the keys are not sorted, nor are listed in the order you added them to the dictionary!**_ If you want to do that, you should sort the keys first

In [18]:
for key in sorted(fruits.keys()):
    print(key, fruits[key])

apples 3
bananas no bananas
oranges 100
pineapples D


In [30]:
for value in sorted(fruits.values(), key = lambda x: str(x)):
    print(value)

100
3
D
no bananas


### Exercise 1
Build a dictionary from the cities list. The key should be the accentless cityname (column 2), The value should be the population

In [38]:
{x : y for x in [1, 2] for y in [1, 3]}

{1: 3, 2: 3}

In [49]:
cd = {c[2] : c[3] for c in cities}

In [54]:
cd = {}
for c in cities:
    cd[c[2]] = c[3]
print(cd['"Budapest"'])

1740041


### Exercise 2
Build a dictionary from the cities list. The key should be the accentless cityname (column 2), The value should be a dictionary, with 'population' the population and 'area' the size in km$^2$

### Numpy
Efficient arary operations, matrix algebra

In [55]:
import numpy as np
a = np.arange(10)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [56]:
import sys
b = [1,2,3]
print(type(b),b,b[0])
a = np.array(b)
print(type(a),a,a[0])

<class 'list'> [1, 2, 3] 1
<class 'numpy.ndarray'> [1 2 3] 1


#### reshape, dimension

In [57]:
a = np.array([1,2,3,4,5,6])
b = np.array([[1,2,3],[4,5,6]])
print(np.ndim(a),np.ndim(b))
c = a.reshape(2,3)
print(c,np.ndim(c))

1 2
[[1 2 3]
 [4 5 6]] 2


#### Data type

In [58]:
a = np.zeros((2,3),dtype=int)
# string of length 20
b = np.zeros(3,dtype="S20")
print("a=",a)
a[0][1] = 1
a[1, 1] = 2
b[2] = "alma"
b[1] = "1234567890123456789012"
print("a=",a)
print("b=",b)

a= [[0 0 0]
 [0 0 0]]
a= [[0 1 0]
 [0 2 0]]
b= [b'' b'12345678901234567890' b'alma']


In [59]:
a = np.arange(12).reshape(3,4)
print("a=",a)
print("a[1:,1:]=",a[1:,1:])
print("a[0]=",a[0])

a= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[1:,1:]= [[ 5  6  7]
 [ 9 10 11]]
a[0]= [0 1 2 3]


In [60]:
user = np.dtype([('name','S20'), ('age', 'i1')])
a = np.zeros(5,dtype=user)
a[0][0] = "János Török".encode("utf-8")
a[0][1] = 46
print(a)
print(str(a[0][0],"utf-8"))

[(b'J\xc3\xa1nos T\xc3\xb6r\xc3\xb6k', 46) (b'',  0) (b'',  0) (b'',  0)
 (b'',  0)]
János Török


### Exercise 3
Fill a numpy array with the data from cities by the city name and the population

In [69]:
cities = cities[1:]
citi_sizes = np.zeros(len(cities) ,dtype = int)
i = 0
for c in cities:
    citi_sizes[i] = c[3]
    i += 1
citi_sizes

array([170052, 166823, 156801, ...,     44,     43,     23])

In [ ]:
citytype = np.dtype([('name','S100'), ('population', 'int')])
cit = np.zeros(len(cities) - 1,dtype=citytype)

#### Random numbers
* seed: the pseudo random generator starts with this number. Always the same sequence
* np.random.random -> uniform random number from 0 to 1

In [70]:
np.random.seed(12345)
a = np.random.random(10)
print(a)

[0.92961609 0.31637555 0.18391881 0.20456028 0.56772503 0.5955447
 0.96451452 0.6531771  0.74890664 0.65356987]


In [71]:
a = np.random.random(10)
print(a)

[0.74771481 0.96130674 0.0083883  0.10644438 0.29870371 0.65641118
 0.80981255 0.87217591 0.9646476  0.72368535]


#### do something with probability p

In [79]:
N = 10
p = 0.2
a = np.random.random(N)
for _dummy in range(N):
    if a[_dummy] < p:
        print("It happened")

It happened
It happened


In [96]:
a = np.random.random((3,3))
print(a)
b = np.zeros((3, 3), dtype = int)
for i in range(3):
    for j in range(3):
        b[i][j] = int(5 * a[i][j])
b

[[0.40039478 0.5871714  0.44415892]
 [0.23392343 0.63421166 0.22923241]
 [0.25145111 0.97857056 0.44660267]]


array([[2, 2, 2],
       [1, 3, 1],
       [1, 4, 2]])

In [81]:
print(np.random.randint(10,size=(2,2)))
print(np.random.normal(1,2,size=(2,2)))
print(np.random.normal(loc=1,scale=2,size=(2,2)))

[[2 0]
 [5 7]]
[[0.7368448  2.8248283 ]
 [1.37642136 5.33892288]]
[[0.77014359 5.00739472]
 [1.0592203  2.59050631]]


#### Choose values

In [98]:
print(np.random.choice(5, 10))
print(np.random.choice(5,3,replace=False))
print(np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]))
c = ["Budapest", "Pécs", "Debrecen", "Miskolc"]
print(np.random.choice(c,1))

[4 2 2 1 3 0 3 1 2 3]
[0 2 3]
[3 3 3 2 3 3 3 2 3 2]
['Debrecen']


#### Operations

In [85]:
a = np.arange(9).reshape((3,3))
b = np.array([1,0,1])
print(a, b)
print("2*a=",2 * a)
print("a+1=",a + 1)
print("a+b=",a + b)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [1 0 1]
2*a= [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
a+1= [[1 2 3]
 [4 5 6]
 [7 8 9]]
a+b= [[1 1 3]
 [4 4 6]
 [7 7 9]]


### Exercise 4
Play around with the previous example (you may want to make a copy) by changing the size of the arrays to see what is allowed

In [99]:
a = np.arange(9).reshape((3,3))
b = np.array([1,0,1])
print(a.transpose())
print("a*a=", a * a)
c = a #copies the position in the memory
c[0] = 9
print("a=", a)
d = np.copy(a)
d[0] = 0
print("a=",a,"\nd=",d)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
a*a= [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
a= [[9 9 9]
 [3 4 5]
 [6 7 8]]
a= [[9 9 9]
 [3 4 5]
 [6 7 8]] 
d= [[0 0 0]
 [3 4 5]
 [6 7 8]]


In [100]:
a = np.arange(9).reshape((3,3))
print("a=",a)
print("sin=",np.sin(a))
print("x**3=",np.power(a,3))
print("sum=",np.sum(a))
print("mean=",np.mean(a))
print("size=",np.size(a))
print("min=",np.min(a))

a= [[0 1 2]
 [3 4 5]
 [6 7 8]]
sin= [[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825]]
x**3= [[  0   1   8]
 [ 27  64 125]
 [216 343 512]]
sum= 36
mean= 4.0
size= 9
min= 0


In [101]:
np.random.seed(12347)
a = np.random.random((3,3))
print(a)
print("minpos=",a.argmin())
print(np.unravel_index(a.argmin(), a.shape))

[[0.70314858 0.53777293 0.24899575]
 [0.53447177 0.63177465 0.59582506]
 [0.22969347 0.343245   0.21629193]]
minpos= 8
(2, 2)


In [102]:
a = np.random.random(6)
index = np.random.randint(6,size=5)
print(a)
print(index)
print(a[index])

[0.12600718 0.56937756 0.42732685 0.83697244 0.53887746 0.61897624]
[0 3 2 3 5]
[0.12600718 0.83697244 0.42732685 0.83697244 0.61897624]


#### Mask out elements, FILTERING

In [103]:
a = np.random.random(6)
mask = np.zeros(6,dtype=bool)
mask[0:2] = True
print("a=",a)
print("mask=",mask)
print("a[mask]=",a[mask])

a= [0.93938244 0.71649087 0.67530051 0.20742662 0.16882031 0.241138  ]
mask= [ True  True False False False False]
a[mask]= [0.93938244 0.71649087]


### Ecercise 5
* Count the number of elements which are less than 0.5
* Replace all elements which are less than 0.5 with new random number

In [117]:
a = np.random.random(10)
mask = np.zeros(10, dtype = bool)
mask[a < 0.5] = True
a[mask] = np.random.random(sum(mask))
a

array([0.71647319, 0.61796811, 0.59254395, 0.86015423, 0.797715  ,
       0.54283698, 0.00192116, 0.73325856, 0.78041303, 0.34619242])

In [114]:

a[a < 0.5] = np.random.random(a[a < 0.5].size)
a

array([0.93023298, 0.55897546, 0.87554133, 0.76938662, 0.19239809,
       0.61504054, 0.66822879, 0.947894  , 0.54366894, 0.79183565])

In [ ]:
print(np.arange(10))
print(np.arange(5,7,0.1))
print(np.linspace(5,7,9))
print(np.logspace(0,2,10))
print(np.logspace(np.log10(0.3),np.log10(28),10))

#### Histogram

In [ ]:
a = np.random.random(10)
h = np.histogram(a, bins=[0, 0.5, 1.0])
print(a)
print(h)

In [ ]:
a = np.random.random(10000)
h = np.histogram(a, bins=[0, 0.5, 1.0])
print(h[0])

### Exercise 6
* Create a histogram divided into 20 bins using linspace
* Create a histogram of normally distributed random numbers use 20 bins, check for the smallest and the largest value first

In [ ]:
import matplotlib.pyplot as plt
x = np.arange(10)
y = x**2
plt.figure()
plt.plot(x, y, '-')
plt.xlabel('x')
plt.ylabel('y')
plt.title('title')
plt.show()

In [ ]:
plt.figure()
plt.plot(x, y, 'r*-')
plt.xlabel('x')
plt.ylabel('y')
plt.title('title')
plt.show()

### fromat of plot
use: <a href="https://matplotlib.org/2.1.1/api/_as_gen/matplotlib.pyplot.plot.html">Mathplotlib plot help</a>

### Exercise 7
* Plot a sin function from -6 to +6
* Plot a sin and a cos function together

#### histograms

In [ ]:
x = np.random.normal(2,1,10000)
plt.hist(x, 50, density=1, facecolor='g')
plt.show()

In [ ]:
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(15,5))
x = np.random.normal(2,1,10000)
true_or_false = True
for ax in axes:
    ax.hist(x, 50, density=true_or_false, facecolor='g')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_title('title')
    true_or_false ^= True



In [ ]:
x = np.random.normal(2,1,10000)
plt.hist(x, 50, density=1, histtype='step')
plt.yscale('log')
plt.show()

### Exercise 8
* Create a random number series of 0 and 1
* Count the length of the successive 1-s (e.g. 0111010 the first sequence has a length of 3 the second has a length of 1)
* Plot a histogram from these values

#### Curve fitting

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Seed the random number generator for reproducibility
np.random.seed(12345)

x_data = np.linspace(-6, 6, num=50)
y_data = 2.5 * np.sin(1.5 * x_data) + np.random.normal(size=50) / 2

# And plot it
plt.figure(figsize=(6, 4))
plt.scatter(x_data, y_data)
plt.show()

In [ ]:
from scipy import optimize

def test_func(x, a, b):
    return a * np.sin(b * x)

params, params_covariance = optimize.curve_fit(test_func, x_data, y_data,
                                               p0=[2, 2])

print(params)

In [ ]:
plt.figure()
plt.scatter(x_data, y_data, label='Data')
plt.plot(x_data, test_func(x_data, params[0], params[1]),
         label='Fitted function')

plt.legend(loc='upper left')
axes = plt.gca()
axes.set_ylim([-3.2,4.5])
plt.show()